a = {'current': 1, 'limit': 20, 'count': 333107, 'list': [
    {'id': 1305157, 'prodName': '大白菜', 'prodCatid': 1186, 'prodCat': '蔬菜', 'prodPcatid': None, 'prodPcat': '',
     'lowPrice': '0.25', 'highPrice': '0.35', 'avgPrice': '0.3', 'place': '冀', 'specInfo': '', 'unitInfo': '斤',
     'pubDate': '2022-07-13 00:00:00', 'status': None, 'userIdCreate': 138, 'userIdModified': None,
     'userCreate': 'admin', 'userModified': None, 'gmtCreate': None, 'gmtModified': None},
    {'id': 1305156, 'prodName': '娃娃菜', 'prodCatid': 1186, 'prodCat': '蔬菜', 'prodPcatid': None, 'prodPcat': '',
     'lowPrice': '0.6', 'highPrice': '0.7', 'avgPrice': '0.65', 'place': '冀', 'specInfo': '大', 'unitInfo': '斤',
     'pubDate': '2022-07-13 00:00:00', 'status': None, 'userIdCreate': 138, 'userIdModified': None,
     'userCreate': 'admin', 'userModified': None, 'gmtCreate': None, 'gmtModified': None},
    {'id': 1305155, 'prodName': '小白菜', 'prodCatid': 1186, 'prodCat': '蔬菜', 'prodPcatid': None, 'prodPcat': '',
     'lowPrice': '3.0', 'highPrice': '3.5', 'avgPrice': '3.25', 'place': '冀', 'specInfo': '', 'unitInfo': '斤',
     'pubDate': '2022-07-13 00:00:00', 'status': None, 'userIdCreate': 138, 'userIdModified': None,
     'userCreate': 'admin', 'userModified': None, 'gmtCreate': None, 'gmtModified': None},
    {'id': 1305154, 'prodName': '圆白菜', 'prodCatid': 1186, 'prodCat': '蔬菜', 'prodPcatid': None, 'prodPcat': '',
     'lowPrice': '0.9', 'highPrice': '1.1', 'avgPrice': '1.0', 'place': '冀', 'specInfo': '', 'unitInfo': '斤',
     'pubDate': '2022-07-13 00:00:00', 'status': None, 'userIdCreate': 138, 'userIdModified': None,
     'userCreate': 'admin', 'userModified': None, 'gmtCreate': None, 'gmtModified': None},
    {'id': 1305153, 'prodName': '紫甘蓝', 'prodCatid': 1186, 'prodCat': '蔬菜', 'prodPcatid': None, 'prodPcat': '',
     'lowPrice': '0.8', 'highPrice': '0.9', 'avgPrice': '0.85', 'place': '冀', 'specInfo': '', 'unitInfo': '斤',
     'pubDate': '2022-07-13 00:00:00', 'status': None, 'userIdCreate': 138, 'userIdModified': None,
     'userCreate': 'admin', 'userModified': None, 'gmtCreate': None, 'gmtModified': None},
    {'id': 1305152, 'prodName': '芹菜', 'prodCatid': 1186, 'prodCat': '蔬菜', 'prodPcatid': None, 'prodPcat': '',
     'lowPrice': '1.5', 'highPrice': '1.8', 'avgPrice': '1.65', 'place': '冀京', 'specInfo': '', 'unitInfo': '斤',
     'pubDate': '2022-07-13 00:00:00', 'status': None, 'userIdCreate': 138, 'userIdModified': None,
     'userCreate': 'admin', 'userModified': None, 'gmtCreate': None, 'gmtModified': None},
    {'id': 1305151, 'prodName': '西芹', 'prodCatid': 1186, 'prodCat': '蔬菜', 'prodPcatid': None, 'prodPcat': '',
     'lowPrice': '1.8', 'highPrice': '2.2', 'avgPrice': '2.0', 'place': '豫辽', 'specInfo': '', 'unitInfo': '斤',
     'pubDate': '2022-07-13 00:00:00', 'status': None, 'userIdCreate': 138, 'userIdModified': None,
     'userCreate': 'admin', 'userModified': None, 'gmtCreate': None, 'gmtModified': None},
    {'id': 1305150, 'prodName': '菠菜', 'prodCatid': 1186, 'prodCat': '蔬菜', 'prodPcatid': None, 'prodPcat': '',
     'lowPrice': '2.5', 'highPrice': '3.0', 'avgPrice': '2.75', 'place': '冀蒙', 'specInfo': '', 'unitInfo': '斤',
     'pubDate': '2022-07-13 00:00:00', 'status': None, 'userIdCreate': 138, 'userIdModified': None,
     'userCreate': 'admin', 'userModified': None, 'gmtCreate': None, 'gmtModified': None},
    {'id': 1305149, 'prodName': '莴笋', 'prodCatid': 1186, 'prodCat': '蔬菜', 'prodPcatid': None, 'prodPcat': '',
     'lowPrice': '1.0', 'highPrice': '1.3', 'avgPrice': '1.15', 'place': '冀津', 'specInfo': '', 'unitInfo': '斤',
     'pubDate': '2022-07-13 00:00:00', 'status': None, 'userIdCreate': 138, 'userIdModified': None,
     'userCreate': 'admin', 'userModified': None, 'gmtCreate': None, 'gmtModified': None},
    {'id': 1305148, 'prodName': '团生菜', 'prodCatid': 1186, 'prodCat': '蔬菜', 'prodPcatid': None, 'prodPcat': '',
     'lowPrice': '1.0', 'highPrice': '1.5', 'avgPrice': '1.25', 'place': '京冀', 'specInfo': '白球\\净', 'unitInfo': '斤',
     'pubDate': '2022-07-13 00:00:00', 'status': None, 'userIdCreate': 138, 'userIdModified': None,
     'userCreate': 'admin', 'userModified': None, 'gmtCreate': None, 'gmtModified': None},
    {'id': 1305147, 'prodName': '散叶生菜', 'prodCatid': 1186, 'prodCat': '蔬菜', 'prodPcatid': None, 'prodPcat': '',
     'lowPrice': '1.8', 'highPrice': '2.2', 'avgPrice': '2.0', 'place': '冀', 'specInfo': '毛\\净', 'unitInfo': '斤',
     'pubDate': '2022-07-13 00:00:00', 'status': None, 'userIdCreate': 138, 'userIdModified': None,
     'userCreate': 'admin', 'userModified': None, 'gmtCreate': None, 'gmtModified': None},
    {'id': 1305146, 'prodName': '罗马生菜', 'prodCatid': 1186, 'prodCat': '蔬菜', 'prodPcatid': None, 'prodPcat': '',
     'lowPrice': '1.8', 'highPrice': '2.2', 'avgPrice': '2.0', 'place': '冀', 'specInfo': '', 'unitInfo': '斤',
     'pubDate': '2022-07-13 00:00:00', 'status': None, 'userIdCreate': 138, 'userIdModified': None,
     'userCreate': 'admin', 'userModified': None, 'gmtCreate': None, 'gmtModified': None},
    {'id': 1305145, 'prodName': '油菜', 'prodCatid': 1186, 'prodCat': '蔬菜', 'prodPcatid': None, 'prodPcat': '',
     'lowPrice': '2.0', 'highPrice': '2.5', 'avgPrice': '2.25', 'place': '鲁京', 'specInfo': '大棵\\小棵', 'unitInfo': '斤',
     'pubDate': '2022-07-13 00:00:00', 'status': None, 'userIdCreate': 138, 'userIdModified': None,
     'userCreate': 'admin', 'userModified': None, 'gmtCreate': None, 'gmtModified': None},
    {'id': 1305144, 'prodName': '香菜', 'prodCatid': 1186, 'prodCat': '蔬菜', 'prodPcatid': None, 'prodPcat': '',
     'lowPrice': '3.5', 'highPrice': '5.0', 'avgPrice': '4.25', 'place': '冀吉', 'specInfo': '', 'unitInfo': '斤',
     'pubDate': '2022-07-13 00:00:00', 'status': None, 'userIdCreate': 138, 'userIdModified': None,
     'userCreate': 'admin', 'userModified': None, 'gmtCreate': None, 'gmtModified': None},
    {'id': 1305143, 'prodName': '茴香', 'prodCatid': 1186, 'prodCat': '蔬菜', 'prodPcatid': None, 'prodPcat': '',
     'lowPrice': '3.5', 'highPrice': '5.0', 'avgPrice': '4.25', 'place': '冀', 'specInfo': '', 'unitInfo': '斤',
     'pubDate': '2022-07-13 00:00:00', 'status': None, 'userIdCreate': 138, 'userIdModified': None,
     'userCreate': 'admin', 'userModified': None, 'gmtCreate': None, 'gmtModified': None},
    {'id': 1305142, 'prodName': '韭菜', 'prodCatid': 1186, 'prodCat': '蔬菜', 'prodPcatid': None, 'prodPcat': '',
     'lowPrice': '2.0', 'highPrice': '2.5', 'avgPrice': '2.25', 'place': '冀', 'specInfo': '', 'unitInfo': '斤',
     'pubDate': '2022-07-13 00:00:00', 'status': None, 'userIdCreate': 138, 'userIdModified': None,
     'userCreate': 'admin', 'userModified': None, 'gmtCreate': None, 'gmtModified': None},
    {'id': 1305141, 'prodName': '苦菊', 'prodCatid': 1186, 'prodCat': '蔬菜', 'prodPcatid': None, 'prodPcat': '',
     'lowPrice': '4.0', 'highPrice': '6.0', 'avgPrice': '5.0', 'place': '冀辽', 'specInfo': '', 'unitInfo': '斤',
     'pubDate': '2022-07-13 00:00:00', 'status': None, 'userIdCreate': 138, 'userIdModified': None,
     'userCreate': 'admin', 'userModified': None, 'gmtCreate': None, 'gmtModified': None},
    {'id': 1305140, 'prodName': '油麦菜', 'prodCatid': 1186, 'prodCat': '蔬菜', 'prodPcatid': None, 'prodPcat': '',
     'lowPrice': '2.5', 'highPrice': '3.5', 'avgPrice': '3.0', 'place': '冀', 'specInfo': '', 'unitInfo': '斤',
     'pubDate': '2022-07-13 00:00:00', 'status': None, 'userIdCreate': 138, 'userIdModified': None,
     'userCreate': 'admin', 'userModified': None, 'gmtCreate': None, 'gmtModified': None},
    {'id': 1305139, 'prodName': '散菜花', 'prodCatid': 1186, 'prodCat': '蔬菜', 'prodPcatid': None, 'prodPcat': '',
     'lowPrice': '2.0', 'highPrice': '3.0', 'avgPrice': '2.5', 'place': '冀', 'specInfo': '散装\\筐装', 'unitInfo': '斤',
     'pubDate': '2022-07-13 00:00:00', 'status': None, 'userIdCreate': 138, 'userIdModified': None,
     'userCreate': 'admin', 'userModified': None, 'gmtCreate': None, 'gmtModified': None},
    {'id': 1305138, 'prodName': '绿菜花', 'prodCatid': 1186, 'prodCat': '蔬菜', 'prodPcatid': None, 'prodPcat': '',
     'lowPrice': '1.5', 'highPrice': '2.2', 'avgPrice': '1.85', 'place': '苏豫冀', 'specInfo': '', 'unitInfo': '斤',
     'pubDate': '2022-07-13 00:00:00', 'status': None, 'userIdCreate': 138, 'userIdModified': None,
     'userCreate': 'admin', 'userModified': None, 'gmtCreate': None, 'gmtModified': None}]}
